### ISSUE TITLE
How we can set direction top to bottom of chart

### ISSUE THREAD

**Issue by sw-ms-pradipbaria** [dabeng/ng-orgchart#18]
I see all sample are with left to right direction. Can anyone let me know how I can set direction from top to bottom.
Thanks

**Comment by ChiKaLiO** [comment]
did you figure it out ?

**Comment by sw-ms-pradipbaria** [comment]
Nope, I switched to jQuery version as it have rich features implemented.

**Comment by ChiKaLiO** [comment]
> Nope, I switched to jQuery version as it have rich features implemented.

can you post an example for how it works with angular ?
